### ISSUE TITLE
sndfile-spectrogram produces poor spectrograms for some inputs.

### ISSUE THREAD

**Issue by erikd** [erikd/sndfile-tools#15]
For instance this pair of commands produces a spectrogram with a bunch of rubbish in it.

    $ sndfile-generate-chirp -amp 1.0 -linear -from 22000 -to 26000 96000 10 chirp96.wav
    Start frequency :  22000.0 Hz (1.439897 rad/sec)
    End   frequency :  26000.0 Hz (1.701696 rad/sec)
    $ sndfile-spectrogram chirp96.wav 800 600 chirp96.png

**Comment by martinwguy** [comment]
The output can be greatly improved by replacing the Kaiser window function with a Hanning window.
I tried the (unused) nuttall window in the sndfile-tools source, which is better and on the chirp gives bristles to the line instead of full-height lines.

However of these two and the 10 windows offered by Audacity for spectrogram display (Rectangular, Bartlett, Hamming, Hanning, Blackman, Blackman-Harris, Welch and three Gaussian), Hanning is the most detailed and noise-free and, for a pure sine tone, gives the most vertically-symmettrical output of the other 11 window functions.

**Comment by martinwguy** [comment]
I've tried changing the window function in case it was related to that, both with success

Kaiser window:
![chirp96-kaiser](https://cloud.githubusercontent.com/assets/608929/11613796/4fe1988e-9c2e-11e5-9f54-db9b3ba8f32f.png)
Nuttall window (enabled from oxbow code in the source):
![chirp96-nuttall](https://cloud.githubusercontent.com/assets/608929/11613798/5c78ed2c-9c2e-11e5-9897-20ae347055a8.png)
Hanning window from WikiPedia { data [k] = 0.5 * (1.0 - cos(2.0 * M_PI * k / (datalen - 1))); }
![chirp96-hanning](https://cloud.githubusercontent.com/assets/608929/11613801/61956f92-9c2e-11e5-9b3e-c1ac6385782f.png)
It looks from these that the Nuttall window gives better frequency-domain separation than Hanning, though Kaiser is even tighter that that.

Is this a property of the Kaiser window itself, to resonate at certain frequencies?
Zooming in on one of the frequency bands, it looks chaotic.
24025-24075:
![chirp24025-24075-kaiser](https://cloud.githubusercontent.com/assets/608929/11614220/0d995878-9c3c-11e5-99ac-fae0825c3eef.png)
24050-24056:
![chirp24050-24056-kaiser](https://cloud.githubusercontent.com/assets/608929/11614221/29b3f96e-9c3c-11e5-92af-54150189303c.png)

**Comment by erikd** [comment]
Thanks. Applied.

**Comment by martinwguy** [comment]
This issue is still with us unfortunately, just rarer with the other two
Analysing http://martinwguy.co.uk/test/51Hz.wav
sndfile-spectrogram --kaiser --no-border --dyn-range=100 51Hz.wav 480 7056 51Hz-kaiser-480-480.png
![51hz-kaiser-480-480](https://cloud.githubusercontent.com/assets/608929/11721650/1b76c81e-9f65-11e5-970f-ce040459a631.png)
sndfile-spectrogram --nuttall --no-border --dyn-range=100 51Hz.wav 480 7056 51Hz-nuttall-480-480.png
![51hz-nuttall-480-480](https://cloud.githubusercontent.com/assets/608929/11721654/216f268a-9f65-11e5-8e09-232f536713bc.png)

**Comment by erikd** [comment]
The is an extremely artificial signal. I think what you are seeing is the effect of the transient at the onset of sine tone.

**Comment by martinwguy** [comment]
i wish what you sas were true, but I get these effects all the time in
analyses of real music, which is how I came to create a simple and
obvious test-case for debugging purposes.

My purpose is wikidelia.net/wiki/Audio and if you have a look, you
will see these florets corrupting the output in most of the pieces.

    M

**Comment by martinwguy** [comment]
I don't think it's the onset (which is brusque, yes) because the erroneous vertical lines only appear when the FFT window only covers an area with pure 50Hz sine tone. It's only when a constant 50Hz tone is the only signal in town that the effect occurs, the same as with the "chirp" test piece. A gut felling says "integer overflow", but it can't be because we are in floating point world!

**Comment by erikd** [comment]
For the 50Hz signal, I wonder is the window length is too small to capture a full cycle of the sine wave.

**Comment by erikd** [comment]
A good experiment would be to do exactly this test for something around 200Hz> If there is no problem there, then reduce the frequency until it becomes a problem.

That might give us an idea what `speclen` should actually be.

**Comment by martinwguy** [comment]
Thanks for the input. 
Hypothesis: For the 50Hz signal, the window length is too small to capture a full cycle of the sine wave.
The test piece is at 44100 samples per second so a 50th of a second is 44100/50=882 samples. The above tests select spec_len==2880 so it has 3 cycles in its window.
Experiment: run the test on a 200Hz tone. It uses speclen=2880 again, so 1 cycle is 220 samples, 2880/220==13 cycles in-window
sndfile-spectrogram --no-border --dyn-range=100 200Hz.wav 480 480 200Hz-kaiser-480-480.png
![200hz-kaiser-480-480](https://cloud.githubusercontent.com/assets/608929/11743929/d75fb56c-a00b-11e5-94f5-500eca34ab6d.png)
Observation: The defect persists so it's not that it has only part of a cycle in-window.

**Comment by martinwguy** [comment]
Observation: It's very sensitive to tiny changes in --dyn-range. For the above tests, --dyn-range=100. Without --dyn-range the artifacts are replaced by a different kind of noise:
![200hz-kaiser-480-200-nodyn](https://cloud.githubusercontent.com/assets/608929/11744250/0e5817b4-a00f-11e5-86d1-980f80e3f56f.png)
and changing dyn_range but a tiny amount radically changes the noise pattern:
--dyn-range=102:
![200hz-kaiser-480-200-dyn102](https://cloud.githubusercontent.com/assets/608929/11744308/7923d132-a00f-11e5-8be4-cd48bb937941.png)
Hypothesis: It's a defect in the colour mapping code, not in the FFT output.
Experiment: Try the test with --gray-scale
sndfile-spectrogram --no-border --dyn-range=100 --gray-scale 200Hz.wav 480 200 200Hz-kaiser-480-200-gray.png
![200hz-kaiser-480-200-gray](https://cloud.githubusercontent.com/assets/608929/11744366/097d1aa4-a010-11e5-8f04-959b6aee3c2c.png)
Observation: Hypothesis confirmed!

**Comment by erikd** [comment]
Ok, I'm going to break the `get_colour_map_value` function into a separate file and write some tests for it.

**Comment by erikd** [comment]
Please test commit:

    commit a3ff738653410e42267bfab7db5e6caca3e7df26
    Author: Erik de Castro Lopo <erikd@mega-nerd.com>
    Date:   Sat Dec 12 20:11:10 2015 +1100

    src/spectrogram.c: Fix colour map calculation

I think that may have fixed it.

**Comment by erikd** [comment]
Please test commit:

    commit 9ca586748b2029b86a9b225178153953e0698f1e
    Author: Erik de Castro Lopo <erikd@mega-nerd.com>
    Date:   Sat Dec 12 20:11:10 2015 +1100

    src/spectrogram.c: Fix colour map calculation

I think that may have fixed it.

**Comment by martinwguy** [comment]
Yes, that fixes all the above testcases.

**Comment by erikd** [comment]
Wonderful!
